### PR TITLE
Audio check

### PR DESCRIPTION
**Pull request by GraionDilach**
Sorry, I won't have time for this during the weekend, so I copmmiuted up everything I noticed on first sight.

Untested, but might resolve the issues you were having.

### CODE REVIEW

**Comment by 11jo** [comment]
The problem belongs to [ChaosKnight](https://github.com/The-Gate-Project/Askaria-Quest_ChaosKnight-kit/blob/5f29b182e6cee8e584f4e7aa3a00e4a8c0b3d99c/ChaosKnight/setup-ChaosKnight.tp2#L192), not Ishlilkamod.

[Bad timing, I've already made some corrections for Ishilka](https://github.com/The-Gate-Project/Ishlilka_The-Wizard-Slayer/commit/043578dc8e4bea65e0feea206f3afaef94d81a97#diff-7c26f76043245595ce35420ba2c0414ecae124bc75b93c53d480bebdcf750b53), so I don't know what to do to resolve conflit with your pull request.

Do I have to add certain parts of your commit manually and cancel the pull request, or is there another way?

**Edit** : [I am ready to add manually the missing part, just one question](https://github.com/The-Gate-Project/Ishlilka_The-Wizard-Slayer/commit/17414d463a02d4ab8baf48894d4530b73648a2d9) :

- What changes have you made to #Ishy.cre ? 

> **Sorry, I won't have time for this during the weekend**

**Take your time to answer !**

**Comment by GraionDilach** [comment]
> Do I have to add certain parts of your commit manually and cancel the pull request

Intended with this.

> What changes have you made to #Ishy.cre ?

Voided the CRE soundslots. 
image

**Comment by 11jo** [comment]
> Intended with this.

? 
I'm sorry GraionDilach, but I often have trouble understanding your very short sentences, some things that seem logical or naturally understandable to you are beyond my comprehension.


> Voided the CRE soundslots.

Maybe I've misunderstood something, but this addition in tp2 adds the empty sound to #Ishy.cre, so there's no need to modify the file in advance, right ?

I've tried both ways and it results in the cre ending the same way...

**Comment by GraionDilach** [comment]
Oh, you did all of that, okay.

Yes, I intended this to get torn apart and only partially integrated on a step-by-step basis because I wasn't sure what was planned here. I guess this ran it's course then.

**Comment by 11jo** [comment]
Great, thanks you as usual !

**Pull request closed without merging**
